// Zone 5 — collapsible evidence footer for any detail shell.
// Shows the entity_audit_log trail for `subject_kind/subject_id`, plus any
// generation metadata the caller passes in.

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ChevronDown, ChevronUp, ExternalLink, History, Sparkles } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { sb as supabase } from "@/lib/sb";
import { cn } from "@/lib/utils";

interface AuditRow {
  id: string;
  change_type: string;
  field: string | null;
  source: string;
  model: string | null;
  notes: string | null;
  created_at: string;
}

interface Props {
  subjectKind: string;
  subjectId: string;
  generationMetadata?: {
    model?: string | null;
    promptKey?: string | null;
    generatedAt?: string | null;
  } | null;
  className?: string;
  defaultOpen?: boolean;
}

export function EvidenceFooter({
  subjectKind,
  subjectId,
  generationMetadata,
  className,
  defaultOpen = false,
}: Props) {
  const [open, setOpen] = useState(defaultOpen);

  const { data: events = [] } = useQuery<AuditRow[]>({
    queryKey: ["entity_audit_log", subjectKind, subjectId],
    enabled: open && !!subjectId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("entity_audit_log")
        .select("id, change_type, field, source, model, notes, created_at")
        .eq("subject_kind", subjectKind)
        .eq("subject_id", subjectId)
        .order("created_at", { ascending: false })
        .limit(50);
      if (error) return [];
      return (data ?? []) as AuditRow[];
    },
  });

  return (
    <section className={cn("rounded-2xl border border-border bg-surface/40", className)}>
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between gap-2 px-4 py-2.5 text-left"
      >
        <div className="flex items-center gap-2">
          <History className="h-3.5 w-3.5 text-muted-foreground" />
          <span className="text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">
            Evidence · audit · revisions
          </span>
        </div>
        <div className="flex items-center gap-2">
          <Link
            to="/audit"
            search={{ subject_kind: subjectKind, subject_id: subjectId }}
            onClick={(e) => e.stopPropagation()}
            className="inline-flex items-center gap-1 rounded-md border border-border/60 bg-background px-2 py-0.5 text-[10px] font-medium text-muted-foreground hover:text-foreground"
          >
            <ExternalLink className="h-2.5 w-2.5" />
            View in audit
          </Link>
          {open ? (
            <ChevronUp className="h-3.5 w-3.5 text-muted-foreground" />
          ) : (
            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
          )}
        </div>
      </button>

      {open && (
        <div className="border-t border-border/40 p-4 text-xs">
          {generationMetadata && (generationMetadata.model || generationMetadata.promptKey) && (
            <div className="mb-3 flex items-center gap-2 rounded-lg bg-iris-soft/40 px-2.5 py-1.5">
              <Sparkles className="h-3 w-3 text-[color:var(--iris-violet)]" />
              <span className="text-[10px] uppercase tracking-wider text-muted-foreground">Generated by</span>
              {generationMetadata.model && (
                <span className="font-mono text-[10px]">{generationMetadata.model}</span>
              )}
              {generationMetadata.promptKey && (
                <span className="rounded bg-background px-1.5 py-0 font-mono text-[9px] text-muted-foreground">
                  {generationMetadata.promptKey}
                </span>
              )}
              {generationMetadata.generatedAt && (
                <span className="ml-auto text-[10px] text-muted-foreground">
                  {formatDistanceToNow(new Date(generationMetadata.generatedAt), { addSuffix: true })}
                </span>
              )}
            </div>
          )}

          {events.length === 0 ? (
            <p className="py-3 text-center text-[11px] text-muted-foreground">
              No audit events recorded for this entity yet.
            </p>
          ) : (
            <ul className="space-y-1.5">
              {events.map((e) => (
                <li
                  key={e.id}
                  className="flex items-start gap-2 rounded-lg border border-border/40 bg-background/40 px-2.5 py-1.5"
                >
                  <span className="rounded-full bg-muted px-1.5 py-0 text-[9px] uppercase tracking-wider text-muted-foreground">
                    {e.change_type}
                  </span>
                  {e.field && (
                    <span className="font-mono text-[10px] text-muted-foreground">{e.field}</span>
                  )}
                  {e.notes && <span className="min-w-0 truncate text-[11px]">{e.notes}</span>}
                  <span className="ml-auto shrink-0 text-[10px] text-muted-foreground">
                    {e.source}
                    {" · "}
                    {formatDistanceToNow(new Date(e.created_at), { addSuffix: true })}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </section>
  );
}
