import { Bot, Cog, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

type GeneratedByKind = "system" | "agent" | "workflow" | null | undefined;

interface SparkProvenanceChipProps {
  kind: GeneratedByKind;
  generatorName?: string | null;
  originEvent?: string | null;
  className?: string;
}

/**
 * Provenance pill for Sparks. Sparks are NEVER human-created — this chip
 * makes the system/agent/workflow origin visible at a glance.
 */
export function SparkProvenanceChip({
  kind,
  generatorName,
  originEvent,
  className,
}: SparkProvenanceChipProps) {
  const k = kind ?? "system";
  const Icon = k === "agent" ? Bot : k === "workflow" ? Cog : Sparkles;
  const label =
    k === "agent"
      ? `Agent · ${generatorName ?? "unknown"}`
      : k === "workflow"
        ? `Workflow · ${generatorName ?? "unknown"}`
        : "System";
  const tone =
    k === "agent"
      ? "border-[color:var(--iris-violet)]/30 bg-iris-soft/40 text-foreground"
      : k === "workflow"
        ? "border-amber-500/30 bg-amber-500/10 text-foreground"
        : "border-border bg-muted/60 text-muted-foreground";
  return (
    <span
      title={originEvent ?? "Generated by the SweetBOS system"}
      className={cn(
        "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-medium",
        tone,
        className,
      )}
    >
      <Icon className="h-3 w-3" />
      {label}
      {originEvent && (
        <span className="ml-1 max-w-[12rem] truncate text-muted-foreground">· {originEvent}</span>
      )}
    </span>
  );
}
