import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

const ActivateInput = z.object({
  workflowId: z.string().uuid(),
  relationshipId: z.string().uuid().optional(),
  projectId: z.string().uuid().optional(),
  notes: z.string().optional(),
});

/**
 * Activate a workflow on a relationship (and optionally a project).
 *
 * Creates a `workflow_runs` row with status=planned, and stages a starter
 * Quest as a proposal in the queue (so the user confirms before it lands
 * in the production tables).
 */
export const activateWorkflow = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => ActivateInput.parse(input))
  .handler(async ({ data, context }) => {
    const { supabase: sb, userId } = context;

    // Look up workflow for naming
    const { data: workflow, error: wfErr } = await sb
      .from("workflows")
      .select("id, name, description")
      .eq("id", data.workflowId)
      .maybeSingle();
    if (wfErr || !workflow) {
      return { ok: false as const, error: "Workflow not found" };
    }

    // Optional relationship
    let relationshipName: string | null = null;
    if (data.relationshipId) {
      const { data: rel } = await sb
        .from("relationships")
        .select("name")
        .eq("id", data.relationshipId)
        .maybeSingle();
      relationshipName = rel?.name ?? null;
    }

    // Create the workflow run
    const { data: run, error: runErr } = await sb
      .from("workflow_runs")
      .insert({
        workflow_id: data.workflowId,
        relationship_id: data.relationshipId ?? null,
        project_id: data.projectId ?? null,
        status: "planned",
        progress_pct: 0,
        notes: data.notes ?? null,
        created_by: user.id,
      })
      .select("id")
      .single();
    if (runErr || !run) {
      return { ok: false as const, error: runErr?.message ?? "Failed to create run" };
    }

    // Stage a starter quest as a proposal
    const questName = relationshipName
      ? `${workflow.name} — kickoff for ${relationshipName}`
      : `${workflow.name} — kickoff`;
    await sb.from("proposals").insert({
      entity_type: "quest",
      status: "pending",
      source: "manual",
      source_label: "workflow_activation",
      source_ref: `workflow_run:${run.id}`,
      raw_input: `Activate workflow "${workflow.name}"${
        relationshipName ? ` on ${relationshipName}` : ""
      }`,
      proposed_fields: {
        name: questName,
        description:
          workflow.description ?? `Auto-generated quest from activating ${workflow.name}.`,
        progression_state: "Open",
      },
      confidence: 0.9,
      conflicts: [],
      ai_model: null,
      ai_notes: "Generated by workflow activation. Review and approve to materialize.",
      created_by: user.id,
    });

    return { ok: true as const, runId: run.id };
  });
