/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVaultRouteImport } from './routes/_app.vault'
import { Route as AppTodayRouteImport } from './routes/_app.today'
import { Route as AppSweetsyncRouteImport } from './routes/_app.sweetsync'
import { Route as AppSweetcycleRouteImport } from './routes/_app.sweetcycle'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppPeopleRouteImport } from './routes/_app.people'
import { Route as AppMyTasksRouteImport } from './routes/_app.my-tasks'
import { Route as AppMeasuresRouteImport } from './routes/_app.measures'
import { Route as AppJourneyRouteImport } from './routes/_app.journey'
import { Route as AppFlightdeckRouteImport } from './routes/_app.flightdeck'
import { Route as AppCaptureRouteImport } from './routes/_app.capture'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBizzybotsRouteImport } from './routes/_app.bizzybots'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app.workflows.index'
import { Route as AppTenetsIndexRouteImport } from './routes/_app.tenets.index'
import { Route as AppTasksIndexRouteImport } from './routes/_app.tasks.index'
import { Route as AppSparksIndexRouteImport } from './routes/_app.sparks.index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app.sessions.index'
import { Route as AppSessionTemplatesIndexRouteImport } from './routes/_app.session-templates.index'
import { Route as AppRelationshipsIndexRouteImport } from './routes/_app.relationships.index'
import { Route as AppQuestsIndexRouteImport } from './routes/_app.quests.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppPlaybooksIndexRouteImport } from './routes/_app.playbooks.index'
import { Route as AppPersonasIndexRouteImport } from './routes/_app.personas.index'
import { Route as AppOutcomesIndexRouteImport } from './routes/_app.outcomes.index'
import { Route as AppOperatorsIndexRouteImport } from './routes/_app.operators.index'
import { Route as AppMissionsIndexRouteImport } from './routes/_app.missions.index'
import { Route as AppJourneysIndexRouteImport } from './routes/_app.journeys.index'
import { Route as AppEngagementPlansIndexRouteImport } from './routes/_app.engagement-plans.index'
import { Route as AppDomainsIndexRouteImport } from './routes/_app.domains.index'
import { Route as AppDomainAssessmentsIndexRouteImport } from './routes/_app.domain-assessments.index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app.documents.index'
import { Route as AppDelegationIndexRouteImport } from './routes/_app.delegation.index'
import { Route as AppDecisionsIndexRouteImport } from './routes/_app.decisions.index'
import { Route as AppComponentsIndexRouteImport } from './routes/_app.components.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as PSlugSeedRouteImport } from './routes/p.$slug.seed'
import { Route as AppWorkflowsIdRouteImport } from './routes/_app.workflows.$id'
import { Route as AppTenetsSlugRouteImport } from './routes/_app.tenets.$slug'
import { Route as AppTasksIdRouteImport } from './routes/_app.tasks.$id'
import { Route as AppSparksIdRouteImport } from './routes/_app.sparks.$id'
import { Route as AppSettingsPromptsRouteImport } from './routes/_app.settings.prompts'
import { Route as AppSettingsOpenDecisionsRouteImport } from './routes/_app.settings.open-decisions'
import { Route as AppSettingsLensesRouteImport } from './routes/_app.settings.lenses'
import { Route as AppSettingsExcellenceRouteImport } from './routes/_app.settings.excellence'
import { Route as AppSessionsIdRouteImport } from './routes/_app.sessions.$id'
import { Route as AppSessionTemplatesIdRouteImport } from './routes/_app.session-templates.$id'
import { Route as AppRelationshipsIdRouteImport } from './routes/_app.relationships.$id'
import { Route as AppQuestsIdRouteImport } from './routes/_app.quests.$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'
import { Route as AppPortalsRelationshipIdRouteImport } from './routes/_app.portals.$relationshipId'
import { Route as AppPlaybooksIdRouteImport } from './routes/_app.playbooks.$id'
import { Route as AppPersonasIdRouteImport } from './routes/_app.personas.$id'
import { Route as AppOutcomesIdRouteImport } from './routes/_app.outcomes.$id'
import { Route as AppOperatorsIdRouteImport } from './routes/_app.operators.$id'
import { Route as AppOperateOcdaRouteImport } from './routes/_app.operate.ocda'
import { Route as AppMissionsIdRouteImport } from './routes/_app.missions.$id'
import { Route as AppLibraryJtbdRouteImport } from './routes/_app.library.jtbd'
import { Route as AppJourneysIdRouteImport } from './routes/_app.journeys.$id'
import { Route as AppEngagementPlansIdRouteImport } from './routes/_app.engagement-plans.$id'
import { Route as AppDomainsSlugRouteImport } from './routes/_app.domains.$slug'
import { Route as AppDomainAssessmentsIdRouteImport } from './routes/_app.domain-assessments.$id'
import { Route as AppDocumentsIdRouteImport } from './routes/_app.documents.$id'
import { Route as AppDelegationIdRouteImport } from './routes/_app.delegation.$id'
import { Route as AppDecisionsIdRouteImport } from './routes/_app.decisions.$id'
import { Route as AppComponentsIdRouteImport } from './routes/_app.components.$id'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as AppSettingsLensesIdRouteImport } from './routes/_app.settings.lenses.$id'
import { Route as AppLibraryJtbdIdRouteImport } from './routes/_app.library.jtbd.$id'
import { Route as AppWorkflowsIdRunsRunIdRouteImport } from './routes/_app.workflows.$id.runs.$runId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSweetsyncRoute = AppSweetsyncRouteImport.update({
  id: '/sweetsync',
  path: '/sweetsync',
  getParentRoute: () => AppRoute,
} as any)
const AppSweetcycleRoute = AppSweetcycleRouteImport.update({
  id: '/sweetcycle',
  path: '/sweetcycle',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTasksRoute = AppMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMeasuresRoute = AppMeasuresRouteImport.update({
  id: '/measures',
  path: '/measures',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppFlightdeckRoute = AppFlightdeckRouteImport.update({
  id: '/flightdeck',
  path: '/flightdeck',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBizzybotsRoute = AppBizzybotsRouteImport.update({
  id: '/bizzybots',
  path: '/bizzybots',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenetsIndexRoute = AppTenetsIndexRouteImport.update({
  id: '/tenets/',
  path: '/tenets/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSparksIndexRoute = AppSparksIndexRouteImport.update({
  id: '/sparks/',
  path: '/sparks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionTemplatesIndexRoute =
  AppSessionTemplatesIndexRouteImport.update({
    id: '/session-templates/',
    path: '/session-templates/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelationshipsIndexRoute = AppRelationshipsIndexRouteImport.update({
  id: '/relationships/',
  path: '/relationships/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsIndexRoute = AppQuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybooksIndexRoute = AppPlaybooksIndexRouteImport.update({
  id: '/playbooks/',
  path: '/playbooks/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonasIndexRoute = AppPersonasIndexRouteImport.update({
  id: '/personas/',
  path: '/personas/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutcomesIndexRoute = AppOutcomesIndexRouteImport.update({
  id: '/outcomes/',
  path: '/outcomes/',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorsIndexRoute = AppOperatorsIndexRouteImport.update({
  id: '/operators/',
  path: '/operators/',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsIndexRoute = AppMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysIndexRoute = AppJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => AppRoute,
} as any)
const AppEngagementPlansIndexRoute = AppEngagementPlansIndexRouteImport.update({
  id: '/engagement-plans/',
  path: '/engagement-plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsIndexRoute = AppDomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainAssessmentsIndexRoute =
  AppDomainAssessmentsIndexRouteImport.update({
    id: '/domain-assessments/',
    path: '/domain-assessments/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppDelegationIndexRoute = AppDelegationIndexRouteImport.update({
  id: '/delegation/',
  path: '/delegation/',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsIndexRoute = AppComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const PSlugSeedRoute = PSlugSeedRouteImport.update({
  id: '/p/$slug/seed',
  path: '/p/$slug/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIdRoute = AppWorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTenetsSlugRoute = AppTenetsSlugRouteImport.update({
  id: '/tenets/$slug',
  path: '/tenets/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIdRoute = AppTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSparksIdRoute = AppSparksIdRouteImport.update({
  id: '/sparks/$id',
  path: '/sparks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPromptsRoute = AppSettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsOpenDecisionsRoute =
  AppSettingsOpenDecisionsRouteImport.update({
    id: '/open-decisions',
    path: '/open-decisions',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsLensesRoute = AppSettingsLensesRouteImport.update({
  id: '/lenses',
  path: '/lenses',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsExcellenceRoute = AppSettingsExcellenceRouteImport.update({
  id: '/excellence',
  path: '/excellence',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSessionsIdRoute = AppSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionTemplatesIdRoute = AppSessionTemplatesIdRouteImport.update({
  id: '/session-templates/$id',
  path: '/session-templates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRelationshipsIdRoute = AppRelationshipsIdRouteImport.update({
  id: '/relationships/$id',
  path: '/relationships/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsIdRoute = AppQuestsIdRouteImport.update({
  id: '/quests/$id',
  path: '/quests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalsRelationshipIdRoute =
  AppPortalsRelationshipIdRouteImport.update({
    id: '/portals/$relationshipId',
    path: '/portals/$relationshipId',
    getParentRoute: () => AppRoute,
  } as any)
const AppPlaybooksIdRoute = AppPlaybooksIdRouteImport.update({
  id: '/playbooks/$id',
  path: '/playbooks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonasIdRoute = AppPersonasIdRouteImport.update({
  id: '/personas/$id',
  path: '/personas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOutcomesIdRoute = AppOutcomesIdRouteImport.update({
  id: '/outcomes/$id',
  path: '/outcomes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorsIdRoute = AppOperatorsIdRouteImport.update({
  id: '/operators/$id',
  path: '/operators/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOperateOcdaRoute = AppOperateOcdaRouteImport.update({
  id: '/operate/ocda',
  path: '/operate/ocda',
  getParentRoute: () => AppRoute,
} as any)
const AppMissionsIdRoute = AppMissionsIdRouteImport.update({
  id: '/missions/$id',
  path: '/missions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryJtbdRoute = AppLibraryJtbdRouteImport.update({
  id: '/library/jtbd',
  path: '/library/jtbd',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysIdRoute = AppJourneysIdRouteImport.update({
  id: '/journeys/$id',
  path: '/journeys/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEngagementPlansIdRoute = AppEngagementPlansIdRouteImport.update({
  id: '/engagement-plans/$id',
  path: '/engagement-plans/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsSlugRoute = AppDomainsSlugRouteImport.update({
  id: '/domains/$slug',
  path: '/domains/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainAssessmentsIdRoute = AppDomainAssessmentsIdRouteImport.update({
  id: '/domain-assessments/$id',
  path: '/domain-assessments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDelegationIdRoute = AppDelegationIdRouteImport.update({
  id: '/delegation/$id',
  path: '/delegation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsIdRoute = AppDecisionsIdRouteImport.update({
  id: '/decisions/$id',
  path: '/decisions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsIdRoute = AppComponentsIdRouteImport.update({
  id: '/components/$id',
  path: '/components/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLensesIdRoute = AppSettingsLensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSettingsLensesRoute,
} as any)
const AppLibraryJtbdIdRoute = AppLibraryJtbdIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLibraryJtbdRoute,
} as any)
const AppWorkflowsIdRunsRunIdRoute = AppWorkflowsIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppWorkflowsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bizzybots': typeof AppBizzybotsRoute
  '/calendar': typeof AppCalendarRoute
  '/capture': typeof AppCaptureRoute
  '/flightdeck': typeof AppFlightdeckRoute
  '/journey': typeof AppJourneyRoute
  '/measures': typeof AppMeasuresRoute
  '/my-tasks': typeof AppMyTasksRoute
  '/people': typeof AppPeopleRoute
  '/pipeline': typeof AppPipelineRoute
  '/planner': typeof AppPlannerRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sweetcycle': typeof AppSweetcycleRoute
  '/sweetsync': typeof AppSweetsyncRoute
  '/today': typeof AppTodayRoute
  '/vault': typeof AppVaultRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/components/$id': typeof AppComponentsIdRoute
  '/decisions/$id': typeof AppDecisionsIdRoute
  '/delegation/$id': typeof AppDelegationIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/domain-assessments/$id': typeof AppDomainAssessmentsIdRoute
  '/domains/$slug': typeof AppDomainsSlugRoute
  '/engagement-plans/$id': typeof AppEngagementPlansIdRoute
  '/journeys/$id': typeof AppJourneysIdRoute
  '/library/jtbd': typeof AppLibraryJtbdRouteWithChildren
  '/missions/$id': typeof AppMissionsIdRoute
  '/operate/ocda': typeof AppOperateOcdaRoute
  '/operators/$id': typeof AppOperatorsIdRoute
  '/outcomes/$id': typeof AppOutcomesIdRoute
  '/personas/$id': typeof AppPersonasIdRoute
  '/playbooks/$id': typeof AppPlaybooksIdRoute
  '/portals/$relationshipId': typeof AppPortalsRelationshipIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/quests/$id': typeof AppQuestsIdRoute
  '/relationships/$id': typeof AppRelationshipsIdRoute
  '/session-templates/$id': typeof AppSessionTemplatesIdRoute
  '/sessions/$id': typeof AppSessionsIdRoute
  '/settings/excellence': typeof AppSettingsExcellenceRoute
  '/settings/lenses': typeof AppSettingsLensesRouteWithChildren
  '/settings/open-decisions': typeof AppSettingsOpenDecisionsRoute
  '/settings/prompts': typeof AppSettingsPromptsRoute
  '/sparks/$id': typeof AppSparksIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/tenets/$slug': typeof AppTenetsSlugRoute
  '/workflows/$id': typeof AppWorkflowsIdRouteWithChildren
  '/p/$slug/seed': typeof PSlugSeedRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/components/': typeof AppComponentsIndexRoute
  '/decisions/': typeof AppDecisionsIndexRoute
  '/delegation/': typeof AppDelegationIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/domain-assessments/': typeof AppDomainAssessmentsIndexRoute
  '/domains/': typeof AppDomainsIndexRoute
  '/engagement-plans/': typeof AppEngagementPlansIndexRoute
  '/journeys/': typeof AppJourneysIndexRoute
  '/missions/': typeof AppMissionsIndexRoute
  '/operators/': typeof AppOperatorsIndexRoute
  '/outcomes/': typeof AppOutcomesIndexRoute
  '/personas/': typeof AppPersonasIndexRoute
  '/playbooks/': typeof AppPlaybooksIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/quests/': typeof AppQuestsIndexRoute
  '/relationships/': typeof AppRelationshipsIndexRoute
  '/session-templates/': typeof AppSessionTemplatesIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/sparks/': typeof AppSparksIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/tenets/': typeof AppTenetsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/library/jtbd/$id': typeof AppLibraryJtbdIdRoute
  '/settings/lenses/$id': typeof AppSettingsLensesIdRoute
  '/workflows/$id/runs/$runId': typeof AppWorkflowsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bizzybots': typeof AppBizzybotsRoute
  '/calendar': typeof AppCalendarRoute
  '/capture': typeof AppCaptureRoute
  '/flightdeck': typeof AppFlightdeckRoute
  '/journey': typeof AppJourneyRoute
  '/measures': typeof AppMeasuresRoute
  '/my-tasks': typeof AppMyTasksRoute
  '/people': typeof AppPeopleRoute
  '/pipeline': typeof AppPipelineRoute
  '/planner': typeof AppPlannerRoute
  '/queue': typeof AppQueueRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sweetcycle': typeof AppSweetcycleRoute
  '/sweetsync': typeof AppSweetsyncRoute
  '/today': typeof AppTodayRoute
  '/vault': typeof AppVaultRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/components/$id': typeof AppComponentsIdRoute
  '/decisions/$id': typeof AppDecisionsIdRoute
  '/delegation/$id': typeof AppDelegationIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/domain-assessments/$id': typeof AppDomainAssessmentsIdRoute
  '/domains/$slug': typeof AppDomainsSlugRoute
  '/engagement-plans/$id': typeof AppEngagementPlansIdRoute
  '/journeys/$id': typeof AppJourneysIdRoute
  '/library/jtbd': typeof AppLibraryJtbdRouteWithChildren
  '/missions/$id': typeof AppMissionsIdRoute
  '/operate/ocda': typeof AppOperateOcdaRoute
  '/operators/$id': typeof AppOperatorsIdRoute
  '/outcomes/$id': typeof AppOutcomesIdRoute
  '/personas/$id': typeof AppPersonasIdRoute
  '/playbooks/$id': typeof AppPlaybooksIdRoute
  '/portals/$relationshipId': typeof AppPortalsRelationshipIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/quests/$id': typeof AppQuestsIdRoute
  '/relationships/$id': typeof AppRelationshipsIdRoute
  '/session-templates/$id': typeof AppSessionTemplatesIdRoute
  '/sessions/$id': typeof AppSessionsIdRoute
  '/settings/excellence': typeof AppSettingsExcellenceRoute
  '/settings/lenses': typeof AppSettingsLensesRouteWithChildren
  '/settings/open-decisions': typeof AppSettingsOpenDecisionsRoute
  '/settings/prompts': typeof AppSettingsPromptsRoute
  '/sparks/$id': typeof AppSparksIdRoute
  '/tasks/$id': typeof AppTasksIdRoute
  '/tenets/$slug': typeof AppTenetsSlugRoute
  '/workflows/$id': typeof AppWorkflowsIdRouteWithChildren
  '/p/$slug/seed': typeof PSlugSeedRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/components': typeof AppComponentsIndexRoute
  '/decisions': typeof AppDecisionsIndexRoute
  '/delegation': typeof AppDelegationIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/domain-assessments': typeof AppDomainAssessmentsIndexRoute
  '/domains': typeof AppDomainsIndexRoute
  '/engagement-plans': typeof AppEngagementPlansIndexRoute
  '/journeys': typeof AppJourneysIndexRoute
  '/missions': typeof AppMissionsIndexRoute
  '/operators': typeof AppOperatorsIndexRoute
  '/outcomes': typeof AppOutcomesIndexRoute
  '/personas': typeof AppPersonasIndexRoute
  '/playbooks': typeof AppPlaybooksIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/quests': typeof AppQuestsIndexRoute
  '/relationships': typeof AppRelationshipsIndexRoute
  '/session-templates': typeof AppSessionTemplatesIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/sparks': typeof AppSparksIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/tenets': typeof AppTenetsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/library/jtbd/$id': typeof AppLibraryJtbdIdRoute
  '/settings/lenses/$id': typeof AppSettingsLensesIdRoute
  '/workflows/$id/runs/$runId': typeof AppWorkflowsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bizzybots': typeof AppBizzybotsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/capture': typeof AppCaptureRoute
  '/_app/flightdeck': typeof AppFlightdeckRoute
  '/_app/journey': typeof AppJourneyRoute
  '/_app/measures': typeof AppMeasuresRoute
  '/_app/my-tasks': typeof AppMyTasksRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/sweetcycle': typeof AppSweetcycleRoute
  '/_app/sweetsync': typeof AppSweetsyncRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/vault': typeof AppVaultRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/components/$id': typeof AppComponentsIdRoute
  '/_app/decisions/$id': typeof AppDecisionsIdRoute
  '/_app/delegation/$id': typeof AppDelegationIdRoute
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/domain-assessments/$id': typeof AppDomainAssessmentsIdRoute
  '/_app/domains/$slug': typeof AppDomainsSlugRoute
  '/_app/engagement-plans/$id': typeof AppEngagementPlansIdRoute
  '/_app/journeys/$id': typeof AppJourneysIdRoute
  '/_app/library/jtbd': typeof AppLibraryJtbdRouteWithChildren
  '/_app/missions/$id': typeof AppMissionsIdRoute
  '/_app/operate/ocda': typeof AppOperateOcdaRoute
  '/_app/operators/$id': typeof AppOperatorsIdRoute
  '/_app/outcomes/$id': typeof AppOutcomesIdRoute
  '/_app/personas/$id': typeof AppPersonasIdRoute
  '/_app/playbooks/$id': typeof AppPlaybooksIdRoute
  '/_app/portals/$relationshipId': typeof AppPortalsRelationshipIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/quests/$id': typeof AppQuestsIdRoute
  '/_app/relationships/$id': typeof AppRelationshipsIdRoute
  '/_app/session-templates/$id': typeof AppSessionTemplatesIdRoute
  '/_app/sessions/$id': typeof AppSessionsIdRoute
  '/_app/settings/excellence': typeof AppSettingsExcellenceRoute
  '/_app/settings/lenses': typeof AppSettingsLensesRouteWithChildren
  '/_app/settings/open-decisions': typeof AppSettingsOpenDecisionsRoute
  '/_app/settings/prompts': typeof AppSettingsPromptsRoute
  '/_app/sparks/$id': typeof AppSparksIdRoute
  '/_app/tasks/$id': typeof AppTasksIdRoute
  '/_app/tenets/$slug': typeof AppTenetsSlugRoute
  '/_app/workflows/$id': typeof AppWorkflowsIdRouteWithChildren
  '/p/$slug/seed': typeof PSlugSeedRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/components/': typeof AppComponentsIndexRoute
  '/_app/decisions/': typeof AppDecisionsIndexRoute
  '/_app/delegation/': typeof AppDelegationIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/domain-assessments/': typeof AppDomainAssessmentsIndexRoute
  '/_app/domains/': typeof AppDomainsIndexRoute
  '/_app/engagement-plans/': typeof AppEngagementPlansIndexRoute
  '/_app/journeys/': typeof AppJourneysIndexRoute
  '/_app/missions/': typeof AppMissionsIndexRoute
  '/_app/operators/': typeof AppOperatorsIndexRoute
  '/_app/outcomes/': typeof AppOutcomesIndexRoute
  '/_app/personas/': typeof AppPersonasIndexRoute
  '/_app/playbooks/': typeof AppPlaybooksIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/quests/': typeof AppQuestsIndexRoute
  '/_app/relationships/': typeof AppRelationshipsIndexRoute
  '/_app/session-templates/': typeof AppSessionTemplatesIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/sparks/': typeof AppSparksIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/tenets/': typeof AppTenetsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/library/jtbd/$id': typeof AppLibraryJtbdIdRoute
  '/_app/settings/lenses/$id': typeof AppSettingsLensesIdRoute
  '/_app/workflows/$id/runs/$runId': typeof AppWorkflowsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bizzybots'
    | '/calendar'
    | '/capture'
    | '/flightdeck'
    | '/journey'
    | '/measures'
    | '/my-tasks'
    | '/people'
    | '/pipeline'
    | '/planner'
    | '/queue'
    | '/settings'
    | '/sweetcycle'
    | '/sweetsync'
    | '/today'
    | '/vault'
    | '/campaigns/$id'
    | '/components/$id'
    | '/decisions/$id'
    | '/delegation/$id'
    | '/documents/$id'
    | '/domain-assessments/$id'
    | '/domains/$slug'
    | '/engagement-plans/$id'
    | '/journeys/$id'
    | '/library/jtbd'
    | '/missions/$id'
    | '/operate/ocda'
    | '/operators/$id'
    | '/outcomes/$id'
    | '/personas/$id'
    | '/playbooks/$id'
    | '/portals/$relationshipId'
    | '/projects/$id'
    | '/quests/$id'
    | '/relationships/$id'
    | '/session-templates/$id'
    | '/sessions/$id'
    | '/settings/excellence'
    | '/settings/lenses'
    | '/settings/open-decisions'
    | '/settings/prompts'
    | '/sparks/$id'
    | '/tasks/$id'
    | '/tenets/$slug'
    | '/workflows/$id'
    | '/p/$slug/seed'
    | '/campaigns/'
    | '/components/'
    | '/decisions/'
    | '/delegation/'
    | '/documents/'
    | '/domain-assessments/'
    | '/domains/'
    | '/engagement-plans/'
    | '/journeys/'
    | '/missions/'
    | '/operators/'
    | '/outcomes/'
    | '/personas/'
    | '/playbooks/'
    | '/projects/'
    | '/quests/'
    | '/relationships/'
    | '/session-templates/'
    | '/sessions/'
    | '/sparks/'
    | '/tasks/'
    | '/tenets/'
    | '/workflows/'
    | '/library/jtbd/$id'
    | '/settings/lenses/$id'
    | '/workflows/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bizzybots'
    | '/calendar'
    | '/capture'
    | '/flightdeck'
    | '/journey'
    | '/measures'
    | '/my-tasks'
    | '/people'
    | '/pipeline'
    | '/planner'
    | '/queue'
    | '/settings'
    | '/sweetcycle'
    | '/sweetsync'
    | '/today'
    | '/vault'
    | '/campaigns/$id'
    | '/components/$id'
    | '/decisions/$id'
    | '/delegation/$id'
    | '/documents/$id'
    | '/domain-assessments/$id'
    | '/domains/$slug'
    | '/engagement-plans/$id'
    | '/journeys/$id'
    | '/library/jtbd'
    | '/missions/$id'
    | '/operate/ocda'
    | '/operators/$id'
    | '/outcomes/$id'
    | '/personas/$id'
    | '/playbooks/$id'
    | '/portals/$relationshipId'
    | '/projects/$id'
    | '/quests/$id'
    | '/relationships/$id'
    | '/session-templates/$id'
    | '/sessions/$id'
    | '/settings/excellence'
    | '/settings/lenses'
    | '/settings/open-decisions'
    | '/settings/prompts'
    | '/sparks/$id'
    | '/tasks/$id'
    | '/tenets/$slug'
    | '/workflows/$id'
    | '/p/$slug/seed'
    | '/campaigns'
    | '/components'
    | '/decisions'
    | '/delegation'
    | '/documents'
    | '/domain-assessments'
    | '/domains'
    | '/engagement-plans'
    | '/journeys'
    | '/missions'
    | '/operators'
    | '/outcomes'
    | '/personas'
    | '/playbooks'
    | '/projects'
    | '/quests'
    | '/relationships'
    | '/session-templates'
    | '/sessions'
    | '/sparks'
    | '/tasks'
    | '/tenets'
    | '/workflows'
    | '/library/jtbd/$id'
    | '/settings/lenses/$id'
    | '/workflows/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bizzybots'
    | '/_app/calendar'
    | '/_app/capture'
    | '/_app/flightdeck'
    | '/_app/journey'
    | '/_app/measures'
    | '/_app/my-tasks'
    | '/_app/people'
    | '/_app/pipeline'
    | '/_app/planner'
    | '/_app/queue'
    | '/_app/settings'
    | '/_app/sweetcycle'
    | '/_app/sweetsync'
    | '/_app/today'
    | '/_app/vault'
    | '/_app/campaigns/$id'
    | '/_app/components/$id'
    | '/_app/decisions/$id'
    | '/_app/delegation/$id'
    | '/_app/documents/$id'
    | '/_app/domain-assessments/$id'
    | '/_app/domains/$slug'
    | '/_app/engagement-plans/$id'
    | '/_app/journeys/$id'
    | '/_app/library/jtbd'
    | '/_app/missions/$id'
    | '/_app/operate/ocda'
    | '/_app/operators/$id'
    | '/_app/outcomes/$id'
    | '/_app/personas/$id'
    | '/_app/playbooks/$id'
    | '/_app/portals/$relationshipId'
    | '/_app/projects/$id'
    | '/_app/quests/$id'
    | '/_app/relationships/$id'
    | '/_app/session-templates/$id'
    | '/_app/sessions/$id'
    | '/_app/settings/excellence'
    | '/_app/settings/lenses'
    | '/_app/settings/open-decisions'
    | '/_app/settings/prompts'
    | '/_app/sparks/$id'
    | '/_app/tasks/$id'
    | '/_app/tenets/$slug'
    | '/_app/workflows/$id'
    | '/p/$slug/seed'
    | '/_app/campaigns/'
    | '/_app/components/'
    | '/_app/decisions/'
    | '/_app/delegation/'
    | '/_app/documents/'
    | '/_app/domain-assessments/'
    | '/_app/domains/'
    | '/_app/engagement-plans/'
    | '/_app/journeys/'
    | '/_app/missions/'
    | '/_app/operators/'
    | '/_app/outcomes/'
    | '/_app/personas/'
    | '/_app/playbooks/'
    | '/_app/projects/'
    | '/_app/quests/'
    | '/_app/relationships/'
    | '/_app/session-templates/'
    | '/_app/sessions/'
    | '/_app/sparks/'
    | '/_app/tasks/'
    | '/_app/tenets/'
    | '/_app/workflows/'
    | '/_app/library/jtbd/$id'
    | '/_app/settings/lenses/$id'
    | '/_app/workflows/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PSlugSeedRoute: typeof PSlugSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sweetsync': {
      id: '/_app/sweetsync'
      path: '/sweetsync'
      fullPath: '/sweetsync'
      preLoaderRoute: typeof AppSweetsyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sweetcycle': {
      id: '/_app/sweetcycle'
      path: '/sweetcycle'
      fullPath: '/sweetcycle'
      preLoaderRoute: typeof AppSweetcycleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-tasks': {
      id: '/_app/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AppMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/measures': {
      id: '/_app/measures'
      path: '/measures'
      fullPath: '/measures'
      preLoaderRoute: typeof AppMeasuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journey': {
      id: '/_app/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flightdeck': {
      id: '/_app/flightdeck'
      path: '/flightdeck'
      fullPath: '/flightdeck'
      preLoaderRoute: typeof AppFlightdeckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capture': {
      id: '/_app/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bizzybots': {
      id: '/_app/bizzybots'
      path: '/bizzybots'
      fullPath: '/bizzybots'
      preLoaderRoute: typeof AppBizzybotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenets/': {
      id: '/_app/tenets/'
      path: '/tenets'
      fullPath: '/tenets/'
      preLoaderRoute: typeof AppTenetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sparks/': {
      id: '/_app/sparks/'
      path: '/sparks'
      fullPath: '/sparks/'
      preLoaderRoute: typeof AppSparksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session-templates/': {
      id: '/_app/session-templates/'
      path: '/session-templates'
      fullPath: '/session-templates/'
      preLoaderRoute: typeof AppSessionTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relationships/': {
      id: '/_app/relationships/'
      path: '/relationships'
      fullPath: '/relationships/'
      preLoaderRoute: typeof AppRelationshipsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests/': {
      id: '/_app/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof AppQuestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbooks/': {
      id: '/_app/playbooks/'
      path: '/playbooks'
      fullPath: '/playbooks/'
      preLoaderRoute: typeof AppPlaybooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personas/': {
      id: '/_app/personas/'
      path: '/personas'
      fullPath: '/personas/'
      preLoaderRoute: typeof AppPersonasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outcomes/': {
      id: '/_app/outcomes/'
      path: '/outcomes'
      fullPath: '/outcomes/'
      preLoaderRoute: typeof AppOutcomesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operators/': {
      id: '/_app/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof AppOperatorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions/': {
      id: '/_app/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AppMissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys/': {
      id: '/_app/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof AppJourneysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engagement-plans/': {
      id: '/_app/engagement-plans/'
      path: '/engagement-plans'
      fullPath: '/engagement-plans/'
      preLoaderRoute: typeof AppEngagementPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/': {
      id: '/_app/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof AppDomainsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domain-assessments/': {
      id: '/_app/domain-assessments/'
      path: '/domain-assessments'
      fullPath: '/domain-assessments/'
      preLoaderRoute: typeof AppDomainAssessmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delegation/': {
      id: '/_app/delegation/'
      path: '/delegation'
      fullPath: '/delegation/'
      preLoaderRoute: typeof AppDelegationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions/': {
      id: '/_app/decisions/'
      path: '/decisions'
      fullPath: '/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/components/': {
      id: '/_app/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AppComponentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$slug/seed': {
      id: '/p/$slug/seed'
      path: '/p/$slug/seed'
      fullPath: '/p/$slug/seed'
      preLoaderRoute: typeof PSlugSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/$id': {
      id: '/_app/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AppWorkflowsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenets/$slug': {
      id: '/_app/tenets/$slug'
      path: '/tenets/$slug'
      fullPath: '/tenets/$slug'
      preLoaderRoute: typeof AppTenetsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$id': {
      id: '/_app/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AppTasksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sparks/$id': {
      id: '/_app/sparks/$id'
      path: '/sparks/$id'
      fullPath: '/sparks/$id'
      preLoaderRoute: typeof AppSparksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/prompts': {
      id: '/_app/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof AppSettingsPromptsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/open-decisions': {
      id: '/_app/settings/open-decisions'
      path: '/open-decisions'
      fullPath: '/settings/open-decisions'
      preLoaderRoute: typeof AppSettingsOpenDecisionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/lenses': {
      id: '/_app/settings/lenses'
      path: '/lenses'
      fullPath: '/settings/lenses'
      preLoaderRoute: typeof AppSettingsLensesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/excellence': {
      id: '/_app/settings/excellence'
      path: '/excellence'
      fullPath: '/settings/excellence'
      preLoaderRoute: typeof AppSettingsExcellenceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/sessions/$id': {
      id: '/_app/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AppSessionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session-templates/$id': {
      id: '/_app/session-templates/$id'
      path: '/session-templates/$id'
      fullPath: '/session-templates/$id'
      preLoaderRoute: typeof AppSessionTemplatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relationships/$id': {
      id: '/_app/relationships/$id'
      path: '/relationships/$id'
      fullPath: '/relationships/$id'
      preLoaderRoute: typeof AppRelationshipsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests/$id': {
      id: '/_app/quests/$id'
      path: '/quests/$id'
      fullPath: '/quests/$id'
      preLoaderRoute: typeof AppQuestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portals/$relationshipId': {
      id: '/_app/portals/$relationshipId'
      path: '/portals/$relationshipId'
      fullPath: '/portals/$relationshipId'
      preLoaderRoute: typeof AppPortalsRelationshipIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbooks/$id': {
      id: '/_app/playbooks/$id'
      path: '/playbooks/$id'
      fullPath: '/playbooks/$id'
      preLoaderRoute: typeof AppPlaybooksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personas/$id': {
      id: '/_app/personas/$id'
      path: '/personas/$id'
      fullPath: '/personas/$id'
      preLoaderRoute: typeof AppPersonasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outcomes/$id': {
      id: '/_app/outcomes/$id'
      path: '/outcomes/$id'
      fullPath: '/outcomes/$id'
      preLoaderRoute: typeof AppOutcomesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operators/$id': {
      id: '/_app/operators/$id'
      path: '/operators/$id'
      fullPath: '/operators/$id'
      preLoaderRoute: typeof AppOperatorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/operate/ocda': {
      id: '/_app/operate/ocda'
      path: '/operate/ocda'
      fullPath: '/operate/ocda'
      preLoaderRoute: typeof AppOperateOcdaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missions/$id': {
      id: '/_app/missions/$id'
      path: '/missions/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof AppMissionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/jtbd': {
      id: '/_app/library/jtbd'
      path: '/library/jtbd'
      fullPath: '/library/jtbd'
      preLoaderRoute: typeof AppLibraryJtbdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys/$id': {
      id: '/_app/journeys/$id'
      path: '/journeys/$id'
      fullPath: '/journeys/$id'
      preLoaderRoute: typeof AppJourneysIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engagement-plans/$id': {
      id: '/_app/engagement-plans/$id'
      path: '/engagement-plans/$id'
      fullPath: '/engagement-plans/$id'
      preLoaderRoute: typeof AppEngagementPlansIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/$slug': {
      id: '/_app/domains/$slug'
      path: '/domains/$slug'
      fullPath: '/domains/$slug'
      preLoaderRoute: typeof AppDomainsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domain-assessments/$id': {
      id: '/_app/domain-assessments/$id'
      path: '/domain-assessments/$id'
      fullPath: '/domain-assessments/$id'
      preLoaderRoute: typeof AppDomainAssessmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delegation/$id': {
      id: '/_app/delegation/$id'
      path: '/delegation/$id'
      fullPath: '/delegation/$id'
      preLoaderRoute: typeof AppDelegationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions/$id': {
      id: '/_app/decisions/$id'
      path: '/decisions/$id'
      fullPath: '/decisions/$id'
      preLoaderRoute: typeof AppDecisionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/components/$id': {
      id: '/_app/components/$id'
      path: '/components/$id'
      fullPath: '/components/$id'
      preLoaderRoute: typeof AppComponentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/lenses/$id': {
      id: '/_app/settings/lenses/$id'
      path: '/$id'
      fullPath: '/settings/lenses/$id'
      preLoaderRoute: typeof AppSettingsLensesIdRouteImport
      parentRoute: typeof AppSettingsLensesRoute
    }
    '/_app/library/jtbd/$id': {
      id: '/_app/library/jtbd/$id'
      path: '/$id'
      fullPath: '/library/jtbd/$id'
      preLoaderRoute: typeof AppLibraryJtbdIdRouteImport
      parentRoute: typeof AppLibraryJtbdRoute
    }
    '/_app/workflows/$id/runs/$runId': {
      id: '/_app/workflows/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflows/$id/runs/$runId'
      preLoaderRoute: typeof AppWorkflowsIdRunsRunIdRouteImport
      parentRoute: typeof AppWorkflowsIdRoute
    }
  }
}

interface AppSettingsLensesRouteChildren {
  AppSettingsLensesIdRoute: typeof AppSettingsLensesIdRoute
}

const AppSettingsLensesRouteChildren: AppSettingsLensesRouteChildren = {
  AppSettingsLensesIdRoute: AppSettingsLensesIdRoute,
}

const AppSettingsLensesRouteWithChildren =
  AppSettingsLensesRoute._addFileChildren(AppSettingsLensesRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsExcellenceRoute: typeof AppSettingsExcellenceRoute
  AppSettingsLensesRoute: typeof AppSettingsLensesRouteWithChildren
  AppSettingsOpenDecisionsRoute: typeof AppSettingsOpenDecisionsRoute
  AppSettingsPromptsRoute: typeof AppSettingsPromptsRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsExcellenceRoute: AppSettingsExcellenceRoute,
  AppSettingsLensesRoute: AppSettingsLensesRouteWithChildren,
  AppSettingsOpenDecisionsRoute: AppSettingsOpenDecisionsRoute,
  AppSettingsPromptsRoute: AppSettingsPromptsRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppLibraryJtbdRouteChildren {
  AppLibraryJtbdIdRoute: typeof AppLibraryJtbdIdRoute
}

const AppLibraryJtbdRouteChildren: AppLibraryJtbdRouteChildren = {
  AppLibraryJtbdIdRoute: AppLibraryJtbdIdRoute,
}

const AppLibraryJtbdRouteWithChildren = AppLibraryJtbdRoute._addFileChildren(
  AppLibraryJtbdRouteChildren,
)

interface AppWorkflowsIdRouteChildren {
  AppWorkflowsIdRunsRunIdRoute: typeof AppWorkflowsIdRunsRunIdRoute
}

const AppWorkflowsIdRouteChildren: AppWorkflowsIdRouteChildren = {
  AppWorkflowsIdRunsRunIdRoute: AppWorkflowsIdRunsRunIdRoute,
}

const AppWorkflowsIdRouteWithChildren = AppWorkflowsIdRoute._addFileChildren(
  AppWorkflowsIdRouteChildren,
)

interface AppRouteChildren {
  AppBizzybotsRoute: typeof AppBizzybotsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCaptureRoute: typeof AppCaptureRoute
  AppFlightdeckRoute: typeof AppFlightdeckRoute
  AppJourneyRoute: typeof AppJourneyRoute
  AppMeasuresRoute: typeof AppMeasuresRoute
  AppMyTasksRoute: typeof AppMyTasksRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppQueueRoute: typeof AppQueueRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSweetcycleRoute: typeof AppSweetcycleRoute
  AppSweetsyncRoute: typeof AppSweetsyncRoute
  AppTodayRoute: typeof AppTodayRoute
  AppVaultRoute: typeof AppVaultRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppComponentsIdRoute: typeof AppComponentsIdRoute
  AppDecisionsIdRoute: typeof AppDecisionsIdRoute
  AppDelegationIdRoute: typeof AppDelegationIdRoute
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
  AppDomainAssessmentsIdRoute: typeof AppDomainAssessmentsIdRoute
  AppDomainsSlugRoute: typeof AppDomainsSlugRoute
  AppEngagementPlansIdRoute: typeof AppEngagementPlansIdRoute
  AppJourneysIdRoute: typeof AppJourneysIdRoute
  AppLibraryJtbdRoute: typeof AppLibraryJtbdRouteWithChildren
  AppMissionsIdRoute: typeof AppMissionsIdRoute
  AppOperateOcdaRoute: typeof AppOperateOcdaRoute
  AppOperatorsIdRoute: typeof AppOperatorsIdRoute
  AppOutcomesIdRoute: typeof AppOutcomesIdRoute
  AppPersonasIdRoute: typeof AppPersonasIdRoute
  AppPlaybooksIdRoute: typeof AppPlaybooksIdRoute
  AppPortalsRelationshipIdRoute: typeof AppPortalsRelationshipIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppQuestsIdRoute: typeof AppQuestsIdRoute
  AppRelationshipsIdRoute: typeof AppRelationshipsIdRoute
  AppSessionTemplatesIdRoute: typeof AppSessionTemplatesIdRoute
  AppSessionsIdRoute: typeof AppSessionsIdRoute
  AppSparksIdRoute: typeof AppSparksIdRoute
  AppTasksIdRoute: typeof AppTasksIdRoute
  AppTenetsSlugRoute: typeof AppTenetsSlugRoute
  AppWorkflowsIdRoute: typeof AppWorkflowsIdRouteWithChildren
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppComponentsIndexRoute: typeof AppComponentsIndexRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
  AppDelegationIndexRoute: typeof AppDelegationIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppDomainAssessmentsIndexRoute: typeof AppDomainAssessmentsIndexRoute
  AppDomainsIndexRoute: typeof AppDomainsIndexRoute
  AppEngagementPlansIndexRoute: typeof AppEngagementPlansIndexRoute
  AppJourneysIndexRoute: typeof AppJourneysIndexRoute
  AppMissionsIndexRoute: typeof AppMissionsIndexRoute
  AppOperatorsIndexRoute: typeof AppOperatorsIndexRoute
  AppOutcomesIndexRoute: typeof AppOutcomesIndexRoute
  AppPersonasIndexRoute: typeof AppPersonasIndexRoute
  AppPlaybooksIndexRoute: typeof AppPlaybooksIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppQuestsIndexRoute: typeof AppQuestsIndexRoute
  AppRelationshipsIndexRoute: typeof AppRelationshipsIndexRoute
  AppSessionTemplatesIndexRoute: typeof AppSessionTemplatesIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppSparksIndexRoute: typeof AppSparksIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppTenetsIndexRoute: typeof AppTenetsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBizzybotsRoute: AppBizzybotsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCaptureRoute: AppCaptureRoute,
  AppFlightdeckRoute: AppFlightdeckRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppMeasuresRoute: AppMeasuresRoute,
  AppMyTasksRoute: AppMyTasksRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppQueueRoute: AppQueueRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSweetcycleRoute: AppSweetcycleRoute,
  AppSweetsyncRoute: AppSweetsyncRoute,
  AppTodayRoute: AppTodayRoute,
  AppVaultRoute: AppVaultRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppComponentsIdRoute: AppComponentsIdRoute,
  AppDecisionsIdRoute: AppDecisionsIdRoute,
  AppDelegationIdRoute: AppDelegationIdRoute,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
  AppDomainAssessmentsIdRoute: AppDomainAssessmentsIdRoute,
  AppDomainsSlugRoute: AppDomainsSlugRoute,
  AppEngagementPlansIdRoute: AppEngagementPlansIdRoute,
  AppJourneysIdRoute: AppJourneysIdRoute,
  AppLibraryJtbdRoute: AppLibraryJtbdRouteWithChildren,
  AppMissionsIdRoute: AppMissionsIdRoute,
  AppOperateOcdaRoute: AppOperateOcdaRoute,
  AppOperatorsIdRoute: AppOperatorsIdRoute,
  AppOutcomesIdRoute: AppOutcomesIdRoute,
  AppPersonasIdRoute: AppPersonasIdRoute,
  AppPlaybooksIdRoute: AppPlaybooksIdRoute,
  AppPortalsRelationshipIdRoute: AppPortalsRelationshipIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppQuestsIdRoute: AppQuestsIdRoute,
  AppRelationshipsIdRoute: AppRelationshipsIdRoute,
  AppSessionTemplatesIdRoute: AppSessionTemplatesIdRoute,
  AppSessionsIdRoute: AppSessionsIdRoute,
  AppSparksIdRoute: AppSparksIdRoute,
  AppTasksIdRoute: AppTasksIdRoute,
  AppTenetsSlugRoute: AppTenetsSlugRoute,
  AppWorkflowsIdRoute: AppWorkflowsIdRouteWithChildren,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppComponentsIndexRoute: AppComponentsIndexRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
  AppDelegationIndexRoute: AppDelegationIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppDomainAssessmentsIndexRoute: AppDomainAssessmentsIndexRoute,
  AppDomainsIndexRoute: AppDomainsIndexRoute,
  AppEngagementPlansIndexRoute: AppEngagementPlansIndexRoute,
  AppJourneysIndexRoute: AppJourneysIndexRoute,
  AppMissionsIndexRoute: AppMissionsIndexRoute,
  AppOperatorsIndexRoute: AppOperatorsIndexRoute,
  AppOutcomesIndexRoute: AppOutcomesIndexRoute,
  AppPersonasIndexRoute: AppPersonasIndexRoute,
  AppPlaybooksIndexRoute: AppPlaybooksIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppQuestsIndexRoute: AppQuestsIndexRoute,
  AppRelationshipsIndexRoute: AppRelationshipsIndexRoute,
  AppSessionTemplatesIndexRoute: AppSessionTemplatesIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppSparksIndexRoute: AppSparksIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppTenetsIndexRoute: AppTenetsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PSlugSeedRoute: PSlugSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
