
-- 1. Re-tag the 8 existing "What is..." quests as reflection
UPDATE public.quests
SET kind = 'reflection', is_template = false
WHERE name LIKE 'What %' AND kind = 'canonical';

-- 2. Seed Quest #1 templates (L1 -> L2)
INSERT INTO public.quests (name, description, journey_id, from_level, to_level, deliverable_type, duration_minutes, quest_number, is_template, kind, scope, progression_state, created_by)
SELECT v.name, v.description, j.id, 'L1 Lacking'::public.maturity_level, 'L2 Learning'::public.maturity_level, v.deliverable_type, v.duration_minutes, 1, true, 'canonical', 'client', 'Not Started'::public.progression_state, '65f0dbf1-d933-43cd-ae2a-50b12b7e9962'::uuid
FROM (VALUES
  ('Define Your Value Proposition',     'Articulate what makes your practice unique and valuable to clients.',         'Strategic Vision & Positioning', 'document', 20),
  ('Build Your Referral System',        'Create a structured approach to generating and tracking referrals.',         'Client Acquisition',             'system',   25),
  ('Map Core Workflows',                'Document your critical business processes.',                                  'Service Design',                 'document', 30),
  ('Define Team Roles',                 'Clarify responsibilities and expectations for your team.',                    'Team Development',               'document', 25),
  ('Audit Your Technology Stack',       'Review all tools and systems you currently use.',                             'Technology Integration',         'document', 25),
  ('Establish Financial Tracking',      'Set up systems to monitor income, expenses, and profitability.',              'Financial Planning (Business)',  'system',   30),
  ('Map Client Experience',             'Document the complete client journey from onboarding to completion.',         'Client Service Delivery',        'document', 30),
  ('Capture Frequently Asked Questions','Document common client questions and your answers.',                          'Operations Management',          'document', 25),
  ('Assess Stress Patterns',            'Identify sources of stress and their impact on you.',                         'Compliance & Risk',              'document', 20),
  ('Audit Your Time Usage',             'Understand how you currently spend your time each week.',                     'Time Management',                'document', 20),
  ('Define Leadership Philosophy',      'Articulate your approach to leadership and team development.',                'Knowledge Management',           'document', 25),
  ('Define Your Vision',                'Articulate where you want your practice to be in 3-5 years.',                 'Performance Tracking',           'document', 25)
) AS v(name, description, journey_name, deliverable_type, duration_minutes)
JOIN public.journeys j ON j.name = v.journey_name
WHERE NOT EXISTS (
  SELECT 1 FROM public.quests q WHERE q.name = v.name AND q.is_template = true
);

-- 3. Seed Quest #2 templates (L2 -> L3)
INSERT INTO public.quests (name, description, journey_id, from_level, to_level, deliverable_type, duration_minutes, quest_number, is_template, kind, scope, progression_state, created_by)
SELECT v.name, v.description, j.id, 'L2 Learning'::public.maturity_level, 'L3 Launching'::public.maturity_level, v.deliverable_type, v.duration_minutes, 2, true, 'canonical', 'client', 'Not Started'::public.progression_state, '65f0dbf1-d933-43cd-ae2a-50b12b7e9962'::uuid
FROM (VALUES
  ('Establish Your Brand Identity',         'Create consistent branding and messaging across all touchpoints.',          'Strategic Vision & Positioning', 'document', 30),
  ('Optimize Prospect Conversion',          'Improve your process for converting prospects to clients.',                 'Client Acquisition',             'strategy', 30),
  ('Automate Repetitive Tasks',             'Implement tools and systems to reduce manual work.',                        'Technology Integration',         'tool',     35),
  ('Build Delegation Systems',              'Create processes to effectively delegate work to your team.',               'Team Development',               'system',   30),
  ('Analyze Service Profitability',         'Understand which services and clients are most profitable.',                'Financial Planning (Business)',  'document', 35),
  ('Create Strategic Roadmap',              'Build a phased plan to achieve your vision.',                               'Performance Tracking',           'strategy', 35),
  ('Enhance Client Communication',          'Improve how you communicate with clients throughout their journey.',        'Client Service Delivery',        'template', 30),
  ('Create Standard Operating Procedures',  'Document how key processes should be executed.',                            'Operations Management',          'sop',      40)
) AS v(name, description, journey_name, deliverable_type, duration_minutes)
JOIN public.journeys j ON j.name = v.journey_name
WHERE NOT EXISTS (
  SELECT 1 FROM public.quests q WHERE q.name = v.name AND q.is_template = true
);

-- 4. Seed Entity Canon for 14 entity kinds
INSERT INTO public.entity_canon (entity_kind, display_name, one_liner, what_it_is, what_good_looks_like, what_bad_looks_like, inputs, outputs, reinforcement_loop, status)
VALUES
  ('quest', 'Quest',
    'A canonical Journey × Level-transition template that advances a Component from one maturity level to the next.',
    'A Quest is a reusable, named template within a Journey that advances a specific Component from one maturity level to the next (e.g. L1 Lacking → L2 Learning). Each Quest has a duration, a deliverable type (document, system, strategy, template, sop, tool), and a clear "done" state. Templates are cloned into instances bound to a relationship.',
    ARRAY['Belongs to a Journey and has a Quest # within it','Declares from_level → to_level (maturity transition)','Has a duration_minutes that matches reality (±20%)','Produces a single named deliverable_type','Lists the Components it advances','Has a clear "Confirmed Complete" definition','Templates are cloneable to relationship instances'],
    ARRAY['No journey or level transition specified','Duration is unset or wildly off','Reads like a freeform prompt instead of a level-transition','Deliverable type is "general" or unset','Cannot be cloned or reused across relationships','Same quest name covers multiple journeys'],
    ARRAY['Sparks (atomic interactions)','Brand canon','Component current maturity'],
    ARRAY['Maturity advancement (one level)','Named deliverable','Audit trail entry'],
    'When a Quest instance hits Confirmed Complete with a high-quality deliverable, optionally promote its pattern back into the template (refining duration, criteria, deliverable). When instances fail criteria, surface as drift and refine the canon.',
    'defined'),
  ('spark', 'Spark',
    'An atomic, system-generated interaction that captures a single signal toward a Component or Quest.',
    'Sparks are the smallest unit of work in the system — a single question, observation, or capture that contributes to a Quest or Component. Sparks are NEVER created by humans directly; they are spawned by Quests, Curators, agents, or workflows.',
    ARRAY['System-generated only (Quest, Curator, agent, or workflow)','Has a clear parent (quest_id or component_id)','Carries provenance: what spawned it, when, with what model','Has a single, narrow purpose — one question or one signal','Inherits scope (internal vs client) from its parent','Can be promoted to a reusable Spark Template when great'],
    ARRAY['Created manually by a human (forbidden)','No parent quest or component','Asks multiple questions in one Spark','Missing provenance or confidence','Duplicate of an existing template that should be reused'],
    ARRAY['Quest','Curator','Agent run','Workflow step'],
    ARRAY['Captured answer','Component contribution','Optional Spark Template'],
    'High-rated Spark instances get promoted to Spark Templates. The deterministic-first generator picks templates over AI-generated Sparks. Drift surfaces as low-rated or unused Sparks.',
    'defined'),
  ('component', 'Component',
    'A reusable, maturity-tracked building block of the practice (L1 Lacking → L5 Leading).',
    'Components are the persistent capabilities the practice is building — Voice of Customer, Strategic Synthesis, Referral System, etc. Each Component has a current maturity level, prerequisite Components, and is advanced by Quests, Sessions, Workflows, and Tasks.',
    ARRAY['Has a clear name and description','Current maturity level is set and recent','Linked to at least one Journey or Domain','Prerequisites are declared','Has a maturity_threshold_definition explaining what "next level" means','Tagged to relevant tenets'],
    ARRAY['No maturity level set','Stale (last_reviewed > 90 days)','Vague description that could mean anything','No prerequisites declared when they obviously exist','Duplicate of another Component with a different name'],
    ARRAY['Quests','Sessions','Workflows','Tasks','Sparks'],
    ARRAY['Maturity advancement','Component outputs (drafts, templates, SOPs)'],
    'When a Component advances levels, the rubric used to advance it is reviewed for tightening. When Components stall, the build pipeline view surfaces them for attention.',
    'defined'),
  ('mission', 'Mission',
    'An overarching transformation goal that spans multiple Journeys and time horizons.',
    'A Mission is the long-arc goal — bigger than a Quest, bigger than a Journey. Missions own related Outcomes and influence which Journeys are prioritized.',
    ARRAY['Has a clear, time-bound horizon','Linked to at least one Outcome','Linked to one or more Journeys','Has a status that reflects current reality','Owner is named'],
    ARRAY['No outcome attached','Vague or aspirational without a horizon','Confused with a Project or a Journey','No owner'],
    ARRAY['Journeys','Outcomes','Strategic decisions'],
    ARRAY['Direction for Journeys and Quests','Outcome completion'],
    'Completed Outcomes auto-mark the Mission as advancing. Stalled Missions trigger a strategic review.',
    'defined'),
  ('outcome', 'Outcome',
    'A measurable result tied back to a Mission, Journey, Quest, Project, or Session.',
    'Outcomes are measurable result types attached polymorphically to a source. They have a target, a current value, and a done_at timestamp.',
    ARRAY['Bound to a source (mission/journey/quest/project/session)','Has a measurable target (number, date, or boolean)','Has a current value or reading journal','Has an owner','Auto-completes when the source completes'],
    ARRAY['No measurable target','Orphan outcome with no source','Target and current value are the same forever','Never auto-completes when source is done'],
    ARRAY['Source entity','Measure readings'],
    ARRAY['Done state','Trend signal'],
    'Outcomes that never close get flagged for refinement. Patterns of incomplete outcomes signal mis-scoping.',
    'defined'),
  ('workflow', 'Workflow',
    'A stored, sequential DAG of steps with operators, deliverables, and human-in-the-loop approval.',
    'Workflows are first-class objects: a sequence of steps with required_role, success_criteria, deliverables, component links, and outcome links.',
    ARRAY['Each step has success_criteria + deliverables','Each step links to Components it advances','Workflow as a whole links to Outcomes','Linked to a Session Template when applicable','Total estimated duration is meaningful','Required role per step is set'],
    ARRAY['Steps with name + description only (no criteria, no deliverables)','No component or outcome links','No session template tied when relevant','Step durations missing or wildly off'],
    ARRAY['Session Template','Component build needs'],
    ARRAY['Workflow runs','Component advancement','Deliverables'],
    'Workflow runs that consistently fail at the same step trigger a workflow refinement review. Successful runs feed back into improved success criteria.',
    'defined'),
  ('session', 'Session',
    'A live or async working block — Mirror, Map, Machine, or Sync — with a phase owner and outputs.',
    'Sessions are time-boxed working units in the SweetCycle. Each session has a sweetcycle_phase, a phase_owner, and produces measurable advances on Components.',
    ARRAY['Has a session_template_id when applicable','sweetcycle_phase and phase_owner are set','Bound to a relationship','Produces at least one captured output','Has a "done" timestamp when complete'],
    ARRAY['No template, no phase, no owner','No captured output after completion','Phase owner contradicts the phase default'],
    ARRAY['Session template','Relationship','Engagement plan'],
    ARRAY['Notes','Decisions','Component advancement','Documents'],
    'Sessions whose outputs match the template''s expected outputs are exemplars. Mismatches surface as template refinement opportunities.',
    'defined'),
  ('operator', 'Operator',
    'A unit of work — a human, an AI agent, or a workflow — with skills, likes, and capacity.',
    'Operators are the canonical "who/what does the work" object. Tasks, workflow steps, and sessions all assign to operator_id.',
    ARRAY['Has a kind (human/agent/workflow)','Skills and dislikes are tagged','Workload visible via operator_workload view','Linked to relevant Components they advance'],
    ARRAY['No kind set','No skills tagged — cannot match to work','Overloaded with no visibility'],
    ARRAY['Skills','Capacity'],
    ARRAY['Completed work','Component advancement'],
    'Operators with high completion rates on a Component become preferred assignees. Bottlenecks surface as workload spikes.',
    'defined'),
  ('domain', 'Domain',
    'One of 22 universal areas of business excellence with maturity scoring per relationship.',
    'Domains are the universal taxonomy. Each relationship gets a maturity score per domain, and Components are tagged to relevant domains.',
    ARRAY['Has color, icon, slug, and clear description','Tagged to relevant Tenets','Has at least one Component built against it','Has at least one rubric defined'],
    ARRAY['No description','No tenets attached','No components ever tagged to it (dead domain)'],
    ARRAY['Domain assessments','Component tagging'],
    ARRAY['Maturity rollup','Build pipeline priorities'],
    'Domains with consistent low maturity across relationships signal an opportunity to build a flagship Component there.',
    'defined'),
  ('tenet', 'Tenet',
    'An industry-specific anchor or principle that constrains how a Component or Quest is built.',
    'Tenets are industry-flavored principles tagged onto Domains, Components, Quests, and Sparks to ensure deliverables respect the industry context.',
    ARRAY['Belongs to one or more Domains','Has a clear, actionable statement','Tagged to at least one Component or Quest'],
    ARRAY['Vague platitude with no actionable edge','No domain attached','Never used by any Component or Quest'],
    ARRAY['Industry knowledge'],
    ARRAY['Quality constraint on outputs'],
    'Tenets that are heavily reused get promoted to Core. Tenets never used get archived.',
    'defined'),
  ('relationship', 'Relationship',
    'A client engagement with a journey, engagement plan, and active SweetCycle stage.',
    'Relationships are the people/companies Liz works with. Each has a current SweetCycle stage, an engagement plan, a service shape, and a journey through the stages.',
    ARRAY['Has a current SweetCycle stage','Has a service_shape','Linked to an engagement_plan when active','Has at least one Project or Session in flight when active'],
    ARRAY['No stage, no service shape','Active but no engagement plan','No activity for >30 days but still "active"'],
    ARRAY['Sessions','Engagement plans','Domain assessments'],
    ARRAY['Components advanced','Outcomes met','Revenue'],
    'Stalled relationships surface in the journey view. Successful patterns inform engagement plan templates.',
    'defined'),
  ('project', 'Project',
    'A bounded unit of work that advances Components and may contain Tasks, Sessions, and Decisions.',
    'Projects are mid-grain work containers — bigger than a Task, smaller than a Mission. They declare which Components they advance.',
    ARRAY['Linked to at least one Component','Has an owner and status','Contains tasks or sessions','Has a clear definition of done'],
    ARRAY['No component links — what is it building?','No owner','Status hasn''t moved in 60+ days'],
    ARRAY['Components to advance','Tasks','Sessions'],
    ARRAY['Component advancement','Decisions','Documents'],
    'Projects that advance Components quickly become reference patterns for new projects.',
    'defined'),
  ('task', 'Task',
    'An atomic, executable unit of work assigned to an operator with status, blocked-flag, and dependencies.',
    'Tasks are the smallest actionable work item. They are NOT Sparks (Sparks are signals; Tasks are executable work).',
    ARRAY['Assigned to an operator (assignee_id)','Has a status','Has a due_date or scheduled_for','Blocked flag is auto-computed from dependencies and waiting_on','Tagged to components/domains when relevant'],
    ARRAY['No assignee','No due date forever','Confused with a Spark (Sparks are system-generated signals, not work)','Stale — no movement in 30+ days'],
    ARRAY['Project','Workflow step','Capture'],
    ARRAY['Done state','Component contribution'],
    'Tasks that consistently get blocked at the same dependency point inform process improvements.',
    'defined'),
  ('journey', 'Journey',
    'A capability area containing Quests that advance maturity within it (e.g. Client Acquisition).',
    'Journeys are the named capability arcs of the practice. Each contains a numbered series of Quest templates that advance Components from L1 toward L5.',
    ARRAY['Has a name and description','Contains at least one canonical Quest template per level transition','Tagged to relevant Domains','Has a clear scope — what it includes and excludes'],
    ARRAY['No quests attached','Quest #1 missing for L1→L2','Overlaps with another Journey without clear separation'],
    ARRAY['Domain knowledge','Maturity rubric'],
    ARRAY['Quest templates','Component advancement'],
    'Journeys that produce reliable maturity gains become the recommended path for new clients.',
    'defined')
ON CONFLICT (entity_kind) DO NOTHING;
